Document: tcl7.3
Title: Debian tcl7.3 Manual
Author: <insert document author here>
Abstract: This manual describes what tcl7.3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tcl7.3/tcl7.3.sgml.gz

Format: postscript
Files: /usr/share/doc/tcl7.3/tcl7.3.ps.gz

Format: text
Files: /usr/share/doc/tcl7.3/tcl7.3.text.gz

Format: HTML
Index: /usr/share/doc/tcl7.3/html/index.html
Files: /usr/share/doc/tcl7.3/html/*.html
