'\" te
.TH tgt_mkdev "1" "" "(TM)"
.ds)H Cosy-Control
.ad b
.SH NAME
.br
.B tgt_mkdev
\- Editieren des Files, in dem Device Treiber Nummern und ihre Namen enthalten sind
.sp
.SH SYNOPSIS
.br
.B tgt_mkdev -[i|d|a]
.sp
.SH BESCHREIBUNG
.br
.B tgt_mkdev 
greift auf den File
.B $TMDB/
.B dev
zu.
.sp 
Folgende Funktionen k\(:onnen ausgef\(:uhrt werden :
.sp
.in 8
.B -i, -d
: Der File kann editiert werden.
.br
.B -a 
: der Inhalt der Datenbank wird ausgegben        
.in 5
.sp
Der File besteht aus 2 Spalten, wobei in der ersten Spalte 
die Majornummer und in der zweiten der Treibername stehen mu\[ss].
.sp 2
Die Environment Variablen
.B CPC
und
.B TMDB
m\(:ussen gesetzt sein.
Die Datenbank mu\[ss] sich in dem Directory
.B $TMDB
befinden.
Ist die Variable TMDB nicht initialisiert, wird sie auf $PWD gesetzt.
.sp
.SH R\(:UCKGABEWERT
.br
- 0 : fehlerfreie Ausf\(:uhrung
.br
- 1 : kein oder ein falsches Argument ist \(:ubergeben worden
.sp
.SH SEITENEFFEKTE
.SH FEHLER
.sp
- es wird kein oder ein falsches Argument \(:ubergeben
.br
.sp
.SH SIEHE AUCH
dev(1)
.sp
.SH WARNUNGEN 
.SH FILES
.SH AUTOR
.nf
Ursula Hilgers,
<ulla@cecs.cc.kfa-juelich.de>
1192
