#!/bin/bash
# %Z%%M%        %I% (mike) %H%
#
# treset
# Load binary images and start target
#
TLOAD_PROG=`basename $0`
export TLOAD_PROG

###############################################################################
# Check for correct parameter count
#
if [ $# -eq 0 ]
then
    echo "USAGE: $TLOAD_PROG target"
    exit 1
fi

###############################################################################
# Variables
#
#CPC=/ccP/cpc

###############################################################################
# MAIN
#

tload -r $*
exit            # return exit status of tload
